config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root to: 'products#index'

  resources :product_categories
  resources :products do
    collection do
      match 'search' => 'products#search', via: [:get, :post], as: :search
    end
  end
  resources :orders
  resources :order_items
  resources :categories
  resource :cart, only: [:show]
  get 'cart/show'

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  devise :database_authenticatable,
         :rememberable, :validatable

  def self.ransackable_attributes(auth_object = nil)
    ["email"]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product_categories
  has_many :products, through: :product_categories

  validates :name, presence: true
  validates :name, uniqueness: true

  private

  def self.ransackable_attributes(auth_object = nil)
    ["name"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["product_categories", "products"]
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, optional: true
  has_many :order_items, dependent: :destroy


  private

  def self.ransackable_associations(auth_object = nil)
    ["order_items", "user"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "id_value", "status", "total_price", "user_id"]
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "id_value", "order_id", "price", "product_id", "quantity", "updated_at"]
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_categories
  has_many :categories, through: :product_categories
  has_one_attached :image

  validates :title, :author, :description, :price, :stock,  presence: true
  validates :price, :stock, numericality: { greater_than_or_equal_to: 0 }

  before_destroy :purge_image
  def purge_image
    image.purge if image.attached?
  end

  before_destroy :delete_product_categories
  def delete_product_categories
    product_categories.destroy_all if product_categories.any?
  end


  private

  def self.ransackable_attributes(auth_object = nil)
    ["author", "description", "id", "id_value", "price", "stock", "title","image_attachment_id","image_blob_id"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["categories", "product_categories"]
  end
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category

  def self.ransackable_attributes(auth_object = nil)
    ["category_id", "created_at", "id", "id_value", "product_id", "updated_at"]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  private

  def self.ransortable_attributes(auth_object = nil)
    column_names - ["encrypted_password"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ransortable_attributes + _ransackers.keys
  end
end

app/controllers/application_controller.rb
# app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :layout_by_resource

  # before_action :authenticate_user!

  helper_method :current_order

  def current_order
    if session[:order_id]
      order = Order.find(session[:order_id])
      if order.status == "pending"
        return order
      else
        session[:order_id] = nil
      end
    end
    if session[:order_id] == nil
      order = Order.create(status: "pending", user: current_user)
      session[:order_id] = order.id
    end
    return order
  end

  private

  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end
end

app/controllers/cart_controller.rb
# app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  private

    def category_params
      params.require(:category).permit(:name)
    end

end

app/controllers/order_items_controller.rb
# app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  def create
    @order = current_order
    @order_item = @order.order_items.new(order_item_params)
    @order.save
    session[:order_id] = @order.id
  end

  def update
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.update_attributes(order_item_params)
    @order_items = @order.order_items
  end

  def destroy
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy
    @order_items = @order.order_items
  end

  private

  def order_item_params
    params.require(:order_item).permit(:product_id, :quantity)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  private

  def order_params
    params.require(:order).permit(:user_id, :total_price, :status)
  end
end

app/controllers/product_categories_controller.rb
class ProductCategoriesController < ApplicationController

  private

  def product_category_params
    params.require(:product_category).permit(:product_id, :category_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_production, only: [:show]

  def index
    @products = Product.order(:title).page(params[:page]).per(20)
  end

  def show
    add_breadcrumb "Home", :root_path
    add_breadcrumb @product.id
    add_breadcrumb @product.title
  end

  def search
    @products = Product.order(:title)

    @products = @products.ransack(title_or_description_cont: params[:query]).result if params[:query].present?

    if params[:c_id].present?
      category = Category.find(params[:c_id])
      @products = @products.joins(:categories).where(categories: { id: category.id })
    end

    @products = @products.page(params[:page]).per(20)

    render :index
  end

  private

  def product_params
    params.require(:product).permit(:title, :author, :description, :price, :stock)
  end

  def set_production
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/product_categories_helper.rb
module ProductCategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cart/show.html.erb
<!-- app/views/cart/show.html.erb -->
<h1>Your Shopping Cart</h1>
<% if @order_items.any? %>
  <table>
    <thead>
      <tr>
        <th>Product</th>
        <th>Quantity</th>
        <th>Price</th>
        <th>Subtotal</th>
      </tr>
    </thead>
    <tbody>
      <% @order_items.each do |item| %>
        <tr>
          <td><%= item.product.title %></td>
          <td><%= item.quantity %></td>
          <td><%= number_to_currency(item.price) %></td>
          <td><%= number_to_currency(item.price * item.quantity) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <h2>Total: <%= number_to_currency(@order_items.sum { |item| item.price * item.quantity }) %></h2>
<% else %>
  <p>Your cart is empty.</p>
<% end %>

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
    <p>
      <%= link_to "Show this category", category %>
    </p>
  <% end %>
</div>

<%= link_to "New category", new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/order_items/_form.html.erb
<%= form_with(model: order_item) do |form| %>
  <% if order_item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(order_item.errors.count, "error") %> prohibited this order_item from being saved:</h2>

      <ul>
        <% order_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :order_id, style: "display: block" %>
    <%= form.text_field :order_id %>
  </div>

  <div>
    <%= form.label :product_id, style: "display: block" %>
    <%= form.text_field :product_id %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/order_items/_order_item.html.erb
<div id="<%= dom_id order_item %>">
  <p>
    <strong>Order:</strong>
    <%= order_item.order_id %>
  </p>

  <p>
    <strong>Product:</strong>
    <%= order_item.product_id %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= order_item.quantity %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= order_item.price %>
  </p>

</div>

app/views/order_items/edit.html.erb
<h1>Editing order item</h1>

<%= render "form", order_item: @order_item %>

<br>

<div>
  <%= link_to "Show this order item", @order_item %> |
  <%= link_to "Back to order items", order_items_path %>
</div>

app/views/order_items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Order items</h1>

<div id="order_items">
  <% @order_items.each do |order_item| %>
    <%= render order_item %>
    <p>
      <%= link_to "Show this order item", order_item %>
    </p>
  <% end %>
</div>

<%= link_to "New order item", new_order_item_path %>

app/views/order_items/new.html.erb
<h1>New order item</h1>

<%= render "form", order_item: @order_item %>

<br>

<div>
  <%= link_to "Back to order items", order_items_path %>
</div>

app/views/order_items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @order_item %>

<div>
  <%= link_to "Edit this order item", edit_order_item_path(@order_item) %> |
  <%= link_to "Back to order items", order_items_path %>

  <%= button_to "Destroy this order item", @order_item, method: :delete %>
</div>

app/views/orders/_form.html.erb
<%= form_with(model: order) do |form| %>
  <% if order.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :total_price, style: "display: block" %>
    <%= form.text_field :total_price %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/_order.html.erb
<div id="<%= dom_id order %>">
  <p>
    <strong>User:</strong>
    <%= order.user_id %>
  </p>

  <p>
    <strong>Total price:</strong>
    <%= order.total_price %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= order.status %>
  </p>

</div>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Show this order", @order %> |
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Orders</h1>

<div id="orders">
  <% @orders.each do |order| %>
    <%= render order %>
    <p>
      <%= link_to "Show this order", order %>
    </p>
  <% end %>
</div>

<%= link_to "New order", new_order_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @order %>

<div>
  <%= link_to "Edit this order", edit_order_path(@order) %> |
  <%= link_to "Back to orders", orders_path %>

  <%= button_to "Destroy this order", @order, method: :delete %>
</div>

app/views/product_categories/_form.html.erb
<%= form_with(model: product_category) do |form| %>
  <% if product_category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product_category.errors.count, "error") %> prohibited this product_category from being saved:</h2>

      <ul>
        <% product_category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :product_id, style: "display: block" %>
    <%= form.text_field :product_id %>
  </div>

  <div>
    <%= form.label :category_id, style: "display: block" %>
    <%= form.text_field :category_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/product_categories/_product_category.html.erb
<div id="<%= dom_id product_category %>">
  <p>
    <strong>Product:</strong>
    <%= product_category.product_id %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= product_category.category_id %>
  </p>

</div>

app/views/product_categories/edit.html.erb
<h1>Editing product category</h1>

<%= render "form", product_category: @product_category %>

<br>

<div>
  <%= link_to "Show this product category", @product_category %> |
  <%= link_to "Back to product categories", product_categories_path %>
</div>

app/views/product_categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Product categories</h1>

<div id="product_categories">
  <% @product_categories.each do |product_category| %>
    <%= render product_category %>
    <p>
      <%= link_to "Show this product category", product_category %>
    </p>
  <% end %>
</div>

<%= link_to "New product category", new_product_category_path %>

app/views/product_categories/new.html.erb
<h1>New product category</h1>

<%= render "form", product_category: @product_category %>

<br>

<div>
  <%= link_to "Back to product categories", product_categories_path %>
</div>

app/views/product_categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product_category %>

<div>
  <%= link_to "Edit this product category", edit_product_category_path(@product_category) %> |
  <%= link_to "Back to product categories", product_categories_path %>

  <%= button_to "Destroy this product category", @product_category, method: :delete %>
</div>

app/views/products/_product.html.erb
 <div class="row gx-4 gx-lg-5 align-items-center">
    <div class="col-md-6">
      <% if product.image.attached? %>
        <%= image_tag product.image.variant(resize_to_limit: [600, 700]), class: "card-img-top mb-5 mb-md-0" %>
      <% else %>
        <img class="card-img-top mb-5 mb-md-0" src="https://dummyimage.com/600x700/dee2e6/6c757d.jpg" alt="..." />
      <% end %>
    </div>

    <div class="col-md-6">
        <h1 class="display-5 fw-bolder"><%= product.title %></h1>
        <div class="fs-5 mb-5">
            <span> <%= number_to_currency(product.price) %></span>
        </div>
        <p class="lead"><%= product.description %></p>
        <div class="d-flex">
            <input class="form-control text-center me-3" id="inputQuantity" type="num" value="1" style="max-width: 3rem" />
            <button class="btn btn-outline-dark flex-shrink-0" type="button">
                <i class="bi-cart-fill me-1"></i>
                Add to cart
            </button>
        </div>
    </div>
  </div>

app/views/products/index.html.erb
<!-- app/views/products/index.html.erb -->
<section>
  <div class="container px-4 px-lg-5 mt-2">
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
      <% @products.each do |product| %>
        <div class="col mb-5">
          <div class="card h-100">
            <!-- Product image-->
            <%= link_to product_path(product) do %>
              <% if product.image.attached? %>
                <%= image_tag product.image.variant(resize_to_limit: [450, nil]), class: "card-img-top" %>
              <% else %>
                 <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
              <% end %>
            <% end %>
            <!-- Product details-->
            <div class="card-body p-4">
                <div class="text-center">
                    <!-- Product name-->
                    <h5 class="fw-bolder"><%= product.title %></h5>
                    <!-- Product reviews-->
                    <div class="d-flex justify-content-center small text-warning mb-2">
                        <div class="bi-star-fill"></div>
                        <div class="bi-star-fill"></div>
                        <div class="bi-star-fill"></div>
                        <div class="bi-star-fill"></div>
                        <div class="bi-star-fill"></div>
                    </div>
                    <!-- Product price-->
                    <%= number_to_currency(product.price) %>
                </div>
            </div>
            <!-- Product actions-->
            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">Add to cart</a></div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

     <%= paginate @products %>
  </div>
</div>

app/views/products/show.html.erb
  <!-- Product section-->
<section class="py-5">
  <div class="container px-4 px-lg-5 my-1">
    <%= render @product %>
  </div>
</section>