config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root to: 'products#index'

  resources :product_categories
  resources :products do
    collection do
      match 'search' => 'products#search', via: [:get, :post], as: :search
    end
  end
  resources :orders
  resources :order_items
  resources :categories
  resource :cart, only: [:show]
  get 'cart/show'

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  devise :database_authenticatable,
         :rememberable, :validatable

  def self.ransackable_attributes(auth_object = nil)
    ["email"]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product_categories
  has_many :products, through: :product_categories

  validates :name, presence: true
  validates :name, uniqueness: true

  private

  def self.ransackable_attributes(auth_object = nil)
    ["name"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["product_categories", "products"]
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, optional: true
  has_many :order_items, dependent: :destroy


  private

  def self.ransackable_associations(auth_object = nil)
    ["order_items", "user"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "id_value", "status", "total_price", "user_id"]
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "id_value", "order_id", "price", "product_id", "quantity", "updated_at"]
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_categories
  has_many :categories, through: :product_categories
  has_one_attached :image

  validates :title, :author, :description, :price, :stock,  presence: true
  validates :price, :stock, numericality: { greater_than_or_equal_to: 0 }

  before_destroy :purge_image
  def purge_image
    image.purge if image.attached?
  end

  before_destroy :delete_product_categories
  def delete_product_categories
    product_categories.destroy_all if product_categories.any?
  end


  private

  def self.ransackable_attributes(auth_object = nil)
    ["author", "description", "id", "id_value", "price", "stock", "title","image_attachment_id","image_blob_id"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["categories", "product_categories"]
  end
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category

  def self.ransackable_attributes(auth_object = nil)
    ["category_id", "created_at", "id", "id_value", "product_id", "updated_at"]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  private

  def self.ransortable_attributes(auth_object = nil)
    column_names - ["encrypted_password"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ransortable_attributes + _ransackers.keys
  end
end

app/controllers/application_controller.rb
# app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :layout_by_resource

  # before_action :authenticate_user!

  helper_method :current_order

  def current_order
    if session[:order_id]
      order = Order.find(session[:order_id])
      if order.status == "pending"
        return order
      else
        session[:order_id] = nil
      end
    end
    if session[:order_id] == nil
      order = Order.create(status: "pending", user: current_user)
      session[:order_id] = order.id
    end
    return order
  end

  private

  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end
end

app/controllers/cart_controller.rb
# app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  private

    def category_params
      params.require(:category).permit(:name)
    end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  private

  def order_params
    params.require(:order).permit(:user_id, :total_price, :status)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_production, only: [:show]

  def index
    @products = Product.order(:title).page(params[:page]).per(20)
  end

  def show
    add_breadcrumb "Home", :root_path
    add_breadcrumb @product.id
    add_breadcrumb @product.title
  end

  def search
    @products = Product.order(:title)

    @products = @products.ransack(title_or_description_cont: params[:query]).result if params[:query].present?

    if params[:c_id].present?
      category = Category.find(params[:c_id])
      @products = @products.joins(:categories).where(categories: { id: category.id })
    end

    @products = @products.page(params[:page]).per(20)

    render :index
  end

  private

  def product_params
    params.require(:product).permit(:title, :author, :description, :price, :stock)
  end

  def set_production
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/product_categories_helper.rb
module ProductCategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WinnipegBookHaven</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <!-- Bootstrap icons-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
  </head>

  <body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container px-lg-5">
        <a class="navbar-brand" href="#!">Winnipeg Book Haven</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto ms-lg-3">
            <li class="nav-item">
              <%= link_to 'Home', root_path, class: 'nav-link active', 'aria-current': 'page' %>
            </li>
            <% Category.all.each do |c| %>
              <li class="nav-item">
                <%= link_to search_products_path(c_id: c.id), class: 'nav-link' do %>
                  <%= c.name %>
                <% end %>
              </li>
            <% end %>
          </ul>
          <ul class="navbar-nav">
            <% if user_signed_in? %>
              <li class="nav-item">
                <span class="nav-link" aria-current="page">
                  <%= link_to 'Sign out', destroy_user_session_path,   data: {turbo_method: :delete} %>
                </span>
              </li>
            <% else %>
              <li class="nav-item">

                <span class="nav-link" aria-current="page">
                  Hello, <%= link_to 'sign in', new_user_session_path %>
                </span>
              </li>
            <% end %>
          </ul>
          <form class="d-flex">
            <button class="btn btn-outline-dark" type="submit">
                <i class="bi-cart-fill me-1"></i>
                Cart
                <span class="badge bg-dark text-white ms-1 rounded-pill">0</span>
            </button>
          </form>
        </div>
      </div>
    </nav>

     <!-- Search bar -->
    <nav class="navbar navbar-light bg-ligh">
      <div class="container px-lg-5 justify-content-start">
        <div class="btn-group">
            <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
              Categories
            </button>
            <ul class="dropdown-menu">
              <li>
                <%= link_to search_products_path, class: 'dropdown-item' do %>
                 All Category
                <% end %>
              </li>
              <li><hr class="dropdown-divider"></li>
              <% Category.all.each do |c| %>
                <li>
                  <%= link_to search_products_path(c_id: c.id), class: 'dropdown-item' do %>
                    <%= c.name %>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
          <%= form_tag search_products_path, method: :get, id: "search_form", class: "form-inline d-flex mx-2" do %>
            <%= hidden_field_tag :c_id, params[:c_id] %>
            <%= text_field_tag :query, params[:query], placeholder: "Search", class: "form-control mr-sm-2" %>
            <button class="btn btn-outline-success my-2 my-sm-0 mx-2" type="submit">Search</button>
        <% end %>
      </div>
    </nav>

    <div class="container px-lg-5">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <%= render_breadcrumbs %>
          </ol>
      </nav>
    </div>
    <!-- Section -->
    <%= yield %>

    <!-- Footer-->
    <footer class="py-5 bg-dark">
      <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p></div>
    </footer>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WinnipegBookHaven</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container d-flex align-items-center justify-content-center vh-100">
      <div class="col-md-4">
         <%= yield %>
      </div>
    </div>
  </body>
</html>